sudo: false

language: node_js

node_js: "12"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

cache:
  yarn: true

jobs:
  include:
    - stage: test
      script:
        - yarn test

    - stage: build library and deploy
      script:
        - yarn build
      before_deploy:
        - ls -1
      deploy:
        - provider: npm
          email: $NPM_EMAIL
          api_key: $NPM_API_KEY
          skip_cleanup: true
          on:
            tags: true
            repo: keboola/eslint-plugin-kbc-ui
            branch: master
      if: tag IS present
