name: Build

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup Node"
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: "Install dependencies"
        run: yarn
      - name: "Run tests"
        run: yarn test
